/*
 * This file is generated by jOOQ.
 */
package com.example.RestaurantManagement.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderManagement implements Serializable {

    private static final long serialVersionUID = 550867326;

    private Integer orderId;
    private String  foodName;
    private String  quantity;
    private Integer price;

    public OrderManagement() {}

    public OrderManagement(OrderManagement value) {
        this.orderId = value.orderId;
        this.foodName = value.foodName;
        this.quantity = value.quantity;
        this.price = value.price;
    }

    public OrderManagement(
        Integer orderId,
        String  foodName,
        String  quantity,
        Integer price
    ) {
        this.orderId = orderId;
        this.foodName = foodName;
        this.quantity = quantity;
        this.price = price;
    }

    public Integer getOrderId() {
        return this.orderId;
    }

    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    public String getFoodName() {
        return this.foodName;
    }

    public void setFoodName(String foodName) {
        this.foodName = foodName;
    }

    public String getQuantity() {
        return this.quantity;
    }

    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    public Integer getPrice() {
        return this.price;
    }

    public void setPrice(Integer price) {
        this.price = price;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrderManagement (");

        sb.append(orderId);
        sb.append(", ").append(foodName);
        sb.append(", ").append(quantity);
        sb.append(", ").append(price);

        sb.append(")");
        return sb.toString();
    }
}
