/*
 * This file is generated by jOOQ.
 */
package com.example.RestaurantManagement.model;


import com.example.RestaurantManagement.model.tables.CustomerManagement;
import com.example.RestaurantManagement.model.tables.OrderManagement;
import com.example.RestaurantManagement.model.tables.RecipeManagement;

import javax.annotation.processing.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index CUSTOMER_PKEY = Indexes0.CUSTOMER_PKEY;
    public static final Index ORDER_MANAGEMENT_PKEY = Indexes0.ORDER_MANAGEMENT_PKEY;
    public static final Index RECIPE_PKEY = Indexes0.RECIPE_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index CUSTOMER_PKEY = Internal.createIndex("customer_pkey", CustomerManagement.CUSTOMER_MANAGEMENT, new OrderField[] { CustomerManagement.CUSTOMER_MANAGEMENT.CUSTOMER_ID }, true);
        public static Index ORDER_MANAGEMENT_PKEY = Internal.createIndex("order_management_pkey", OrderManagement.ORDER_MANAGEMENT, new OrderField[] { OrderManagement.ORDER_MANAGEMENT.ORDER_ID }, true);
        public static Index RECIPE_PKEY = Internal.createIndex("recipe_pkey", RecipeManagement.RECIPE_MANAGEMENT, new OrderField[] { RecipeManagement.RECIPE_MANAGEMENT.RECIPE_ID }, true);
    }
}
