/*
 * This file is generated by jOOQ.
 */
package com.example.RestaurantManagement.model;


import com.example.RestaurantManagement.model.tables.CustomerManagement;
import com.example.RestaurantManagement.model.tables.OrderManagement;
import com.example.RestaurantManagement.model.tables.RecipeManagement;
import com.example.RestaurantManagement.model.tables.records.CustomerManagementRecord;
import com.example.RestaurantManagement.model.tables.records.OrderManagementRecord;
import com.example.RestaurantManagement.model.tables.records.RecipeManagementRecord;

import javax.annotation.processing.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<CustomerManagementRecord, Integer> IDENTITY_CUSTOMER_MANAGEMENT = Identities0.IDENTITY_CUSTOMER_MANAGEMENT;
    public static final Identity<OrderManagementRecord, Integer> IDENTITY_ORDER_MANAGEMENT = Identities0.IDENTITY_ORDER_MANAGEMENT;
    public static final Identity<RecipeManagementRecord, Integer> IDENTITY_RECIPE_MANAGEMENT = Identities0.IDENTITY_RECIPE_MANAGEMENT;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CustomerManagementRecord> CUSTOMER_PKEY = UniqueKeys0.CUSTOMER_PKEY;
    public static final UniqueKey<OrderManagementRecord> ORDER_MANAGEMENT_PKEY = UniqueKeys0.ORDER_MANAGEMENT_PKEY;
    public static final UniqueKey<RecipeManagementRecord> RECIPE_PKEY = UniqueKeys0.RECIPE_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 {
        public static Identity<CustomerManagementRecord, Integer> IDENTITY_CUSTOMER_MANAGEMENT = Internal.createIdentity(CustomerManagement.CUSTOMER_MANAGEMENT, CustomerManagement.CUSTOMER_MANAGEMENT.CUSTOMER_ID);
        public static Identity<OrderManagementRecord, Integer> IDENTITY_ORDER_MANAGEMENT = Internal.createIdentity(OrderManagement.ORDER_MANAGEMENT, OrderManagement.ORDER_MANAGEMENT.ORDER_ID);
        public static Identity<RecipeManagementRecord, Integer> IDENTITY_RECIPE_MANAGEMENT = Internal.createIdentity(RecipeManagement.RECIPE_MANAGEMENT, RecipeManagement.RECIPE_MANAGEMENT.RECIPE_ID);
    }

    private static class UniqueKeys0 {
        public static final UniqueKey<CustomerManagementRecord> CUSTOMER_PKEY = Internal.createUniqueKey(CustomerManagement.CUSTOMER_MANAGEMENT, "customer_pkey", CustomerManagement.CUSTOMER_MANAGEMENT.CUSTOMER_ID);
        public static final UniqueKey<OrderManagementRecord> ORDER_MANAGEMENT_PKEY = Internal.createUniqueKey(OrderManagement.ORDER_MANAGEMENT, "order_management_pkey", OrderManagement.ORDER_MANAGEMENT.ORDER_ID);
        public static final UniqueKey<RecipeManagementRecord> RECIPE_PKEY = Internal.createUniqueKey(RecipeManagement.RECIPE_MANAGEMENT, "recipe_pkey", RecipeManagement.RECIPE_MANAGEMENT.RECIPE_ID);
    }
}
