/*
 * This file is generated by jOOQ.
 */
package com.example.RestaurantManagement.model;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.customer_customer_id_seq</code>
     */
    public static final Sequence<Integer> CUSTOMER_CUSTOMER_ID_SEQ = new SequenceImpl<Integer>("customer_customer_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.order_management_order_id_seq</code>
     */
    public static final Sequence<Integer> ORDER_MANAGEMENT_ORDER_ID_SEQ = new SequenceImpl<Integer>("order_management_order_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.recipe_dish_id_seq</code>
     */
    public static final Sequence<Integer> RECIPE_DISH_ID_SEQ = new SequenceImpl<Integer>("recipe_dish_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
